wandb_version: 1

T_0:
  desc: null
  value: 25
T_max:
  desc: null
  value: 62550
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1680199151.509939
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 71
      - 80
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 71
      - 80
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.14.0
      6: 4.26.0
      8:
      - 1
      - 2
      - 4
      - 5
alpha:
  desc: null
  value: 0.99
backbone:
  desc: null
  value: google/vit-base-patch16-224+sentence-transformers/all-mpnet-base-v2
betas:
  desc: null
  value:
  - 0.9
  - 0.999
competition:
  desc: null
  value: memotions-7k
debug:
  desc: null
  value: false
device:
  desc: null
  value: cpu
epochs:
  desc: null
  value: 50
eps:
  desc: null
  value: 1.0e-06
exp_name:
  desc: null
  value: vit/sbert
image_encoder:
  desc: null
  value: google/vit-base-patch16-224
img_size:
  desc: null
  value:
  - 224
  - 224
learning_rate:
  desc: null
  value: 0.0003
lr_decay:
  desc: null
  value: 0
max_len:
  desc: null
  value: 128
min_lr:
  desc: null
  value: 1.0e-06
model_name:
  desc: null
  value: vit-sbert-multimodal
momentum:
  desc: null
  value: 0
n_accumulate:
  desc: null
  value: 1
num_classes:
  desc: null
  value: null
num_folds:
  desc: null
  value: 5
optimizer:
  desc: null
  value: Adam
rho:
  desc: null
  value: 0.9
scheduler:
  desc: null
  value: CosineAnnealingLR
seed:
  desc: null
  value: 101
tokenizer:
  desc: null
  value: sentence-transformers/all-mpnet-base-v2
train_bs:
  desc: null
  value: 24
valid_bs:
  desc: null
  value: 48
warmup_epochs:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 1.0e-06
